version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50
    groups:
      storybook:
        applies-to: version-updates
        patterns:
          - "@storybook*"
          - "storybook*"
      ag-grid:
        applies-to: version-updates
        patterns:
          - "@ag-grid-community/*"
      fusion-wc:
        applies-to: version-updates
        patterns:
          - "@equinor/fusion-wc-*"
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"