export type FusionDatePickerProps = {
  allowKeyboardControl?: boolean;
  allowSameDay?: boolean;
  date: Date | null | undefined;
  disabled?: boolean;
  disableFuture?: boolean;
  disablePast?: boolean;
  endDate?: Date;
  excludeDates?: Date[];
  excludeTimes?: Date[];
  filterDate?(date: Date): boolean;
  fluid?: boolean;
  includeDates?: Date[];
  includeTimes?: Date[];
  injectTimes?: Date[];
  inline?: boolean;
  isClearable?: boolean;
  locale?: Locale | undefined;
  maxDate?: Date | null;
  maxTime?: Date;
  minDate?: Date | null;
  minTime?: Date;
  onBlur?(): void;
  onChange(date: Date | null): void;
  onClose?(): void;
  onFocus?(): void;
  onMonthChange?(date: Date): void;
  onOpen?(): void;
  onYearChange?(date: Date): void;
  openToDate?: Date;
  placeholder?: string;
  readOnly?: boolean;
  shouldDisableDate?(date: Date): boolean;
  shouldCloseOnSelect?: boolean;
  showTodayButton?: boolean;
  showWeekNumbers?: boolean;
  startDate?: Date;
  startOpen?: boolean;
  tabIndex?: number;
  type?: DatePickerType;
  width?: string;
};

export type DatePickerType = 'year' | 'month' | 'date' | 'datetime' | 'time' | undefined;
