name: Setup Node
description: General setup of node
inputs:
  node-version:  
    description: 'Setting node version'
    default: '22'

runs:
  using: composite
  steps:

    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        registry-url: "https://registry.npmjs.org"

    - name: Install Node Dependencies
      shell: bash
      run: pnpm install