name: Generate Docs

on: 
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v2
        with:
          ref: docs

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org

      - name: Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: update branch
        run: |
          git fetch origin/main
          git merge origin/main

      - name: Install Node Dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm ci
        env:
          CI: TRUE

      - name: Build project
        run: npm run build

      - name: Build storybook
        run: npm run storybook:build

      - name: Commit changes
        run: |
            echo "!docs/" >> .gitignore
            git add docs 
            git commit -m'docs: Build of storybook'
            git push --force
        env:
          GH_TOKEN: ${{ github.token }}