name: Generate Docs

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: docs
          github_token: ${{ github.token }}

  generate-docs:
    runs-on: ubuntu-latest
    needs: merge
    steps:

      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          ref: docs

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Node Dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: pnpm ci --legacy-peer-deps

      - name: Build project
        run: pnpm run build

      - name: Build storybook
        run: |
          rm -rf docs
          pnpm run storybook:build

      - name: Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit changes
        run: |
            echo "!docs/" >> .gitignore
            git add docs 
            git commit -m'docs: build of storybook'
            git push --force