name: Lint project files

on: 
  pull_request:
    paths:
      - '**.ts'
      - '**.tsx'

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install pnpm
        run: npm install pnpm -g

      - name: Install Node Dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Save Code Linting Report JSON
        run: pnpm lint:report
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.1.2
        with:
          repo-token: "${{ github.token }}"
          report-json: "eslint-report.log.json"

      - name: Upload ESLint report
        uses: actions/upload-artifact@v2
        with:
          name: eslint-report.log.json
          path: eslint-report.log.json