name: Lint project files

on: 
  pull_request:
    paths:
      - '**.ts'
      - '**.tsx'

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node and install deps
        uses: ./.github/workflows/actions/node-setup

      - name: Build project
        run: pnpm build

      - name: Save Code Linting Report JSON
        run: pnpm lint:report
        continue-on-error: true

      - uses: actions/upload-artifact@v3
        with:
          name: eslint-report.log.json
          path: eslint-report.log.json

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@2.2.0
        with:
          repo-token: "${{ github.token }}"
          report-json: "eslint-report.log.json"