name: Lint project files

on: 
  pull_request: 
    types: 
      - ready_for_review
      - opened
      - reopened
      - synchronize

jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup node and install deps
        uses: ./.github/workflows/actions/node-setup

      - name: Build project
        run: pnpm build
    
      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2

      - name: Run Biome
        run: biome ci
