name: Post PRs to Teams

on:
  pull_request:
    types:
      - ready_for_review

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Notify Teams channel
        uses: davidwengier/PostAdaptiveCard@v1.0.4
        with:
          webhook_uri: ${{ secrets.TEAMS_PR_WEBHOOK }}